version: "3"
services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DATABASE_LOCAL: AffiliationVisaDB
      POSTGRES_DB: agreement-db
      POSTGRES_HOST_LOCAL: localhost
      POSTGRES_PASSWORD_LOCAL: db_password
      POSTGRES_PASSWORD: db_password
      POSTGRES_PORT_LOCAL: 5432
      POSTGRES_USER: db_user
      POSTGRES_USER_LOCAL: db_user
    volumes:
      - ../users/agreement_app_user.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d agreement-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network
  migrate-up:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./changes:/changes
    command: "-path /changes -database postgres://db_user:db_password@database:5432/agreement-db?sslmode=disable up"
    depends_on:
      database:
        condition: service_healthy
  migrate-down-all:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./changes:/changes
    command: "-path /changes -database postgres://db_user:db_password@database:5432/agreement-db?sslmode=disable down --all"
    depends_on:
      database:
        condition: service_healthy
networks:
  network:
    driver: bridge
