# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure RM'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az postgres flexible-server parameter set --name require_secure_transport --value off --resource-group Migration --server-name affiliationvisa-db'
