jobs:
  - job: PublishToArtifactory
    displayName: Publish to artifactory
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: CopyFiles@2
        displayName: Copy Files
        inputs:
          Contents: |
            teste-db/migrations/**
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
      - task: PublishBuildArtifacts@1
        displayName: Publish build artifact
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: artifact
