jobs:
  - job: RunLocalMigrate
    displayName: Local migrate w/ docker-compose
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerCompose@0
        displayName: up database
        inputs:
          containerregistrytype: Container Registry
          dockerComposeFile: ./teste-db/migrations/docker-compose.yml
          action: Run a Docker Compose command
          qualifyImageNames: true
          dockerComposeCommand: up -d database

      - task: DockerCompose@0
        displayName: up migrate-up
        inputs:
          containerregistrytype: Container Registry
          dockerComposeFile: ./teste-db/migrations/docker-compose.yml
          action: Run a Docker Compose command
          qualifyImageNames: true
          dockerComposeCommand: up --abort-on-container-exit --exit-code-from migrate-up migrate-up

      - task: DockerCompose@0
        displayName: up migrate-down-all
        inputs:
          containerregistrytype: Container Registry
          dockerComposeFile: ./teste-db/migrations/docker-compose.yml
          action: Run a Docker Compose command
          qualifyImageNames: true
          dockerComposeCommand: up --abort-on-container-exit --exit-code-from migrate-down-all migrate-down-all

      - task: DockerCompose@0
        displayName: down
        inputs:
          containerregistrytype: Container Registry
          dockerComposeFile: ./teste-db/migrations/docker-compose.yml
          action: Run a Docker Compose command
          qualifyImageNames: true
          dockerComposeCommand: down
