ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT,USAGE ON SEQUENCES FROM "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE ON TYPES FROM "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON ROUTINES FROM "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES REVOKE USAGE ON SCHEMAS FROM "AffiliationVisaAppUser";
