-- Executar com usuário admin da cloud

CREATE USER "AffiliationVisaAppUser" WITH ENCRYPTED PASSWORD 'Stone@@2023!';
GRANT CONNECT ON DATABASE "AffiliationVisaDB" TO "AffiliationVisaAppUser";

-- Alterando default privileges EXECUTAR NO BANCO "AffiliationVisaDB", logago com o usuário MIGRATIONAPPUSER

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON TYPES TO "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON ROUTINES TO "AffiliationVisaAppUser";
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO "AffiliationVisaAppUser";

-- Alterando default privileges EXECUTAR NO BANCO "AffiliationVisaDB", logago com o usuário MIGRATIONAPPUSER

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO psqladminafl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO psqladminafl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON TYPES TO psqladminafl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO psqladminafl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON ROUTINES TO psqladminafl;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO psqladminafl;
