CREATE USER dpaaflvisauser WITH ENCRYPTED PASSWORD '#{POSTGRES_PASSWORD}#';
ALTER ROLE dpaaflvisauser WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '#{POSTGRES_PASSWORD}#';

CREATE ROLE monitoring;
ALTER ROLE monitoring WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '#{POSTGRES_PASSWORD}#';

CREATE ROLE "buy4-role-databaseservices-operation";
ALTER ROLE "buy4-role-databaseservices-operation" WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;

CREATE ROLE ldap_group;
ALTER ROLE ldap_group WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;

CREATE ROLE replicator;
ALTER ROLE replicator WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN REPLICATION NOBYPASSRLS PASSWORD '#{POSTGRES_PASSWORD}#';

CREATE ROLE dba;
ALTER ROLE dba WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;

GRANT pg_monitor TO monitoring;
GRANT pg_read_all_settings TO dpaaflvisauser;
GRANT pg_read_all_stats TO dpaaflvisauser;
GRANT pg_signal_backend TO dpaaflvisauser;