version: "3"
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: db_name
      POSTGRES_PASSWORD: db_password
      POSTGRES_PORT: 5432
      POSTGRES_USER: db_user
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network
  migrate-up:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./changes:/changes
    command: "-path /changes -database postgres://db_user:db_password@database:5432/db_name?sslmode=disable up"
    depends_on:
      database:
        condition: service_healthy
  migrate-down-all:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./changes:/changes
    command: "-path /changes -database postgres://db_user:db_password@database:5432/db_name?sslmode=disable down --all"
    depends_on:
      database:
        condition: service_healthy
networks:
  network:
    driver: bridge
