trigger:
  branches:
    include:
    - main
  paths:
    include:
    - affiliationvisa-db/Infra

pool:
  vmImage: ubuntu-latest

parameters:
  -VAR_GROUP: Terraform

variables:
- group: Terraform

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: Installer
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure RM'
              backendAzureRmResourceGroupName: '$(resourcegroup)'
              backendAzureRmStorageAccountName: '$(storageaccount)'
              backendAzureRmContainerName: '$(blobcontainer)'
              backendAzureRmKey: '$(terraformstatekey)'
              workingDirectory: '$(terraformdirectory)'
          - task: TerraformTaskV4@4
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps: 
          - task: TerraformInstaller@1
            displayName: Installer
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure RM'
              backendAzureRmResourceGroupName: '$(resourcegroup)'
              backendAzureRmStorageAccountName: '$(storageaccount)'
              backendAzureRmContainerName: '$(blobcontainer)'
              backendAzureRmKey: '$(terraformstatekey)'
              workingDirectory: '$(terraformdirectory)'
          - task: TerraformTaskV4@4
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTaskV4@4
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(terraformdirectory)'
              environmentServiceNameAzureRM: 'Azure RM'
          - task: TerraformTaskV4@4
            displayName: Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(terraformdirectory)'
              environmentServiceNameAzureRM: 'Azure RM'