trigger:
  branches:
    include:
    - main
  paths:
    include:
    - affiliationvisa-db/Infra
pr:
  branches:
    include:
      - main
  paths:
    include:
      - affiliationvisa-db/Infra

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure RM'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az postgres flexible-server parameter set --name require_secure_transport --value off --resource-group Migration --server-name affiliationvisa-db'