trigger:
  branches:
    include:
    - main
  paths:
    include:
    - affiliationvisa-db/Infra
pr:
  branches:
    include:
      - main
  paths:
    include:
      - affiliationvisa-db/Infra

pool:
  vmImage: ubuntu-latest

