trigger:
  branches:
    include:
      - master
  paths:
    include:
      - teste-db/migrations
pr:
  branches:
    include:
      - master
  paths:
    include:
      - teste-db/migrations

stages:
  - stage: CI
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: CI
    jobs:
      - template: jobs/run-local-migrate.yml
      - template: jobs/publish-to-artifactory.yml
      - job: PrintVariables
        displayName: Print Variables
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              echo Command: $(MIGRATE_COMMAND)
              echo Qnt Migrations: $(MIGRATE_NUMBER)
            displayName: Print

  - stage: CDNonProd
    displayName: CD non-prod
    dependsOn: CI
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: jobs/run-migrate.yml
        parameters:
          VAR_GROUP: Migration-STG
          ENVIRONMENT: NonProduction-Infra
          POOL_NAME: "Azure Pipelines"

 # - stage: CDProd
 #   displayName: CD prod
 #   dependsOn: 
 #     - CI
 #     - CDNonProd
 #   condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
 #   jobs:
 #     - template: jobs/run-migrate.yml
 #       parameters:
 #         VAR_GROUP: Migration-PRD
 #         ENVIRONMENT: Production-Infra
 #         POOL_NAME: "Azure Pipelines"
