trigger:
  branches:
    include:
      - main
  paths:
    include:
      - affiliationvisa-db/migrations
pr:
  branches:
    include:
      - main
  paths:
    include:
      - affiliationvisa-db/migrations

stages:
  - stage: CI
    displayName: CI
    jobs:
      #- template: jobs/run-local-migrate.yml
      - template: jobs/publish-to-artifactory.yml
      - job: PrintVariables
        displayName: Print Variables
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              echo Command: $(COMMAND)
              echo Qnt Migrations: $(QNT_MIGRATIONS)
            displayName: Print

  - stage: CDNonProd
    displayName: CD non-prod
    dependsOn: CI
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: jobs/run-migrate.yml
        parameters:
          VAR_GROUP: Migration-STG
          ENVIRONMENT: NonProduction-Infra
          POOL_NAME: "Azure Pipelines"

  #- stage: CDProd
  #  displayName: CD prod
  #  dependsOn: 
  #    - CI
  #    - CDNonProd
  #  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  #  jobs:
  #    - template: jobs/run-migrate.yml
  #      parameters:
  #        VAR_GROUP: Migration-PRD
  #        ENVIRONMENT: Production-Infra
  #        POOL_NAME: "Azure Pipelines"
